[plugin]
repository = "https://github.com/ottercorp/Distance.git"
commit = "62ff6c32ce81885ac972916726c52fac956a30e6"
owners = [
    "PunishedPineapple",
    "MapleRecall"
]
project_path = "Distance"
changelog = '''
- Updated for Dalamud API 12.
'''
