[plugin]
repository = "https://github.com/Loskh/StarlightBreaker.git"
commit = "ea9511bc2856194986240914e7826afe3f7d8c7f"
owners = [
    "Loskh",
]
project_path = "StarlightBreaker.Dalamud"
changelog = "Update API X"
